#!/bin/sh
_lib_8311 2>/dev/null || . /lib/8311.sh


# Configure LCT Interface
uci set "network.lct.auto"="1"
uci set "network.lct.ipaddr"="$(get_8311_ipaddr)"
uci set "network.lct.netmask"="$(get_8311_netmask)"
uci set "network.lct.gateway"="$(get_8311_gateway)"
uci set "network.lct.macaddr"="$(get_8311_lct_mac)"

# Configure IP Host Interface
uci set "network.iphost1.macaddr"="$(get_8311_iphost_mac)"

# Configure WebUI
if [ -d "/usr/lib/lua/luci" ]; then
	uci set "luci.main.mediaurlbase"="/luci-static/bootstrap"
	uci commit "luci"
fi
