#!/bin/sh
_lib_8311 2>/dev/null || . /lib/8311.sh


# Configure LCT Interface
LCT_IFNAME=$(uci get "network.lct.ifname" || echo "eth0_0_1_lct")
LCT_MAC="$(get_8311_lct_mac)"

LCT_DNS=$(get_8311_dns_server)
LCT_VLAN=$(get_8311_lct_vlan)
DB_INT="lct"
if [ "$LCT_VLAN" -gt 0 ] && [ "$LCT_VLAN" -le 4095 ]; then
	DB_INT="mgmt"
	uci set "network.lct_vlan"="device"
	uci set "network.lct_vlan.ifname"="$LCT_IFNAME"
	uci set "network.lct_vlan.name"="mgmt"
	uci set "network.lct_vlan.type"="8021q"
	uci set "network.lct_vlan.vid"="$LCT_VLAN"

	uci set "network.mgmt"="interface"
	uci set "network.mgmt.ifname"="mgmt"
	uci set "network.mgmt.auto"="1"
	uci set "network.mgmt.macaddr"="$LCT_MAC"
	uci set "network.mgmt.proto"="static"
	uci set "network.mgmt.ipaddr"="$(get_8311_ipaddr)"
    uci set "network.mgmt.netmask"="$(get_8311_netmask)"
    uci set "network.mgmt.gateway"="$(get_8311_gateway)"

	[ -n "$LCT_DNS" ] && uci set "network.mgmt.dns"="$LCT_DNS"

	uci del "network.lct.ipaddr"
	uci del "network.lct.netmask"
	uci del "network.lct.gateway"

	uci add_list "firewall.@zone[0].network"="mgmt"
else
	uci set "network.lct.ipaddr"="$(get_8311_ipaddr)"
	uci set "network.lct.netmask"="$(get_8311_netmask)"
	uci set "network.lct.gateway"="$(get_8311_gateway)"
	[ -n "$LCT_DNS" ] && uci set "network.lct.dns"="$LCT_DNS"
fi

uci set "network.lct.auto"="1"
uci set "network.lct.macaddr"="$LCT_MAC"

uci del_list "firewall.@zone[0].network"="lan"
uci commit "firewall"


# Configure IP Host Interface
uci set "network.iphost1.macaddr"="$(get_8311_iphost_mac)"

# Get rid of warnings about delegated IPv6 prefixes
uci delete "network.globals.ula_prefix"


uci commit "network"

# Configure LuCI
LUCI_DIR="/usr/lib/lua/luci"
if [ -d "$LUCI_DIR" ]; then
	TRANS_DIR="$LUCI_DIR/i18n"

	uci set "luci.languages.en"="English"
	[ -f "$TRANS_DIR/8311.zh-cn.lmo" ] && uci set "luci.languages.zh_cn"="简体中文 (Chinese Simplified)"
	[ -f "$TRANS_DIR/8311.ja.lmo" ] && uci set "luci.languages.ja"="日本語 (Japanese)"

	SYS_LANG=$(get_8311_lang)
	uci set "luci.main.lang"="$SYS_LANG"

	[ -d "/www/luci-static/bootstrap" ] && uci set "luci.main.mediaurlbase"="/luci-static/bootstrap"

	uci commit "luci"
fi

SYS_HOSTNAME=$(get_8311_hostname)
if [ -n "$SYS_HOSTNAME" ]; then
	uci set "system.@system[0].hostname"="$SYS_HOSTNAME"
	uci commit "system"
else
	SYS_HOSTNAME="prx126-sfp-pon"
fi

if [ -f "/usr/sbin/dropbear" ]; then
	rm -f "/etc/config/dropbear"
	touch "/etc/config/dropbear"

	uci batch <<BATCH
add dropbear dropbear
set dropbear.@dropbear[0].PasswordAuth='on'
set dropbear.@dropbear[0].RootPasswordAuth='on'
set dropbear.@dropbear[0].Port='22'
set dropbear.@dropbear[0].DirectInterface='$DB_INT'
commit dropbear
BATCH
fi

uci set "sfp_eeprom.factory_bridge.enable"="0"
uci commit "sfp_eeprom"

# Configure Dying Gasp
[ "$(get_8311_dying_gasp_en)" = "1" ] && DG_DIS="0" || DG_DIS="1"
uci set "optic.common.dg_dis"="$DG_DIS"
uci commit "optic"


TIMEZONE=$(get_8311_timezone)
[ -n "$TIMEZONE" ] && uci set "system.@system[0].zonename"="$TIMEZONE"

uci delete "system.ntp.server"
uci set "system.ntp.enable_server"="0"

NTP_ENABLED="0"
NTP_SERVERS=$(get_8311_ntp_servers)
if [ -n "$NTP_SERVERS" ]; then
	NTP_ENABLED="1"
	for NTP_SERVER in $NTP_SERVERS; do
		uci add_list "system.ntp.server"="$NTP_SERVER"
	done
fi
uci set "system.ntp.enabled"="$NTP_ENABLED"
uci commit "system"

if [ -f /usr/sbin/uhttpd ]; then
	REDIR_HTTPS="1"
	[ "$(get_8311_https_redirect)" -eq 0 ] &>/dev/null && REDIR_HTTPS="0"

	uci batch <<EOF
		set uhttpd.main.cert="/ptconf/8311/uhttpd/uhttpd.crt"
		set uhttpd.main.key="/ptconf/8311/uhttpd/uhttpd.key"
		set uhttpd.main.redirect_https="${REDIR_HTTPS}"
		set uhttpd.defaults.key_type="ec"
		set uhttpd.defaults.ec_curve="P-384"
		set uhttpd.defaults.days="3652"
		set uhttpd.defaults.state="8331"
		set uhttpd.defaults.commonname="${SYS_HOSTNAME}"
		set uhttpd.defaults.location="WebUI"
		commit uhttpd
EOF
fi
